### ISSUE TITLE
⬆ Failed to `renice`

### ISSUE THREAD

**Issue by amaya382** [amaya382/docker-mirakurun-chinachu-encoder#4]
```
mirakurun    | 0|mirakuru |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
mirakurun    | 0|mirakuru |     at Module._compile (module.js:570:32)
mirakurun    | 0|mirakuru | Error: Command failed: renice -n -10 -p 189
mirakurun    | 0|mirakuru | renice: setpriority: Permission denied
mirakurun    | 0|mirakuru |
mirakurun    | 0|mirakuru |     at checkExecSyncError (child_process.js:483:13)
mirakurun    | 0|mirakuru |     at Object.execSync (child_process.js:523:13)
mirakurun    | 0|mirakuru |     at Object.<anonymous> (/usr/lib/node_modules/mirakurun/lib/server.ts:51:5)
mirakurun    | 0|mirakuru |     at Module._compile (module.js:570:32)
mirakurun    | 0|mirakuru |     at Object.Module._extensions..js (module.js:579:10)
mirakurun    | 0|mirakuru |     at Module.load (module.js:487:32)
mirakurun    | 0|mirakuru |     at tryModuleLoad (module.js:446:12)
mirakurun    | 0|mirakuru |     at Function.Module._load (module.js:438:3)
mirakurun    | 0|mirakuru |     at Object.<anonymous> (/usr/lib/node_modules/pm2/lib/ProcessContainerFork.js:53:21)
mirakurun    | 0|mirakuru |     at Module._compile (module.js:570:32)
```

**Comment by amaya382** [comment]
明らかに異常なpidを指定している. docker-mirakurun-chinachuでも同様の症状を確認. Mirakurun側のバグの可能性もあり.
